### ISSUE TITLE
Good,Some Questions

### ISSUE THREAD

**Issue by Pkaran01** [sauravpradhan/Basic-Audio-Routing#1]
Hi Saurav your all the app is vary good. specially on BT. You did deep research on BT. I am now working on android app which required sink current playing song in my mobile should be play same song in other device both are connected to BT.  Does your example will help me ya i have to do other thing please can you guide me.
Thanks.

**Comment by sauravpradhan** [comment]
Sorry I did not get your question properly,  but do you mean you want to play same song on two mobiles via BT ?

**Comment by Pkaran01** [comment]
Thanks for quick response. Exactly. user are connected with my application via BT. when one user play song. this should be play on both device at same time. i want sinking between both device via BT..

**Comment by sauravpradhan** [comment]
have not worked in this idea but with some hack we might be able to use other phones speaker as BT speaker ! have to dig and only can answer your question.

**Comment by Pkaran01** [comment]
look at this question.http://stackoverflow.com/questions/33316248/play-mp3-over-bluetooth-network-in-both-device-same-time-in-android

ok thanks. thanks alot. is A2DP work..?

**Comment by sauravpradhan** [comment]
Will be back to Bangalore by next week and will have to see how to make this work. Will definitely try and let you know if it is possible from any logic from my side.

**Comment by sauravpradhan** [comment]
Hey did a little research in this. This needs your own complete logic to be written to buffer your data via either BT or same Wifi network. This requires a lot of work. Meanwhile close this issue here in GitHub. YOu have to set up your own BT Client server logic.
